name: Blueprint Prod Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn test
        env:
          CI: true
      - run: yarn build
      - run: yarn build-storybook
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      - name: Deploy to Surge platform
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'component-frontend-blueprint.surge.sh'
          project: './.storybook-build'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
      - name: Publish to GH Packages
        run: |
          echo "@jozsefDevs:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:always-auth=true" >> .npmrc
          echo "//npm.pkg.github.com/:email=JozsefDevs <jozsefDevs@users.noreply.github.com>" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=$GH_TOKEN" >> .npmrc
          yarn publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
