name: Blueprint Prod Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.16.x'
      - run: yarn install
      - run: yarn build
      - run: yarn test
        env:
            CI: true
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      - name: Deploy to Surge platform
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'ci-cd-frontend-blueprint.surge.sh'
          project: './build'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}