name: Blueprint Staging Build
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.16.x'
      - run: yarn install
      - run: yarn build
      - run: yarn test
        env:
          CI: true
      - name: Deploy to Surge platform
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'ci-cd-frontend-blueprint-staging.surge.sh'
          project: './build'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}